[my-base] Jun 20, 2020 - zhouyu #1
momoyama-south-gate/haskell-codespace pull request #4
Opened 2020-06-20 05:39 UTC by zhouyu843

在开这个 PR 之前请确认以下几点：

# rebase master 了吗？
`git rebase master`
- [ ] 已检查

# PR 标题格式正确吗？（如果是提交作业的话）
`[<package name>] <deadline> (<number of submission>) - <username>`
比如说 `[my-base] Jun 20, 2020 (2) - carassius1014`
- [ ] 已检查

2020-06-20 07:19 UTC, carassius1014 requested changes
除了以上几点 LGTM

2020-06-20 07:19 UTC, carassius1014 commented on my-base/src/My/Data/Either.hs
> +import Data.Bool (not)
`My.Prelude.Internal` 里有了所以不用 import

2020-06-20 07:19 UTC, carassius1014 commented on my-base/src/My/Data/List/NonEmpty.hs
> +instance Applicative NonEmpty where
添加测试！

2020-06-20 07:19 UTC, carassius1014 commented on my-base/src/My/Data/Maybe.hs
> +import Data.Bool (not)
这里也不用 `import`

2020-06-20 08:12 UTC, carassius1014 requested changes
除了 `My.Data.List` LGTM

2020-06-20 08:12 UTC, carassius1014 commented on my-base/src/My/Data/List.hs
> +words xs = reverse $ go xs [] [] where
`\t\r` 之类的间隔符还有待支持。然后多写几个测试。

2020-06-23 10:57 UTC, carassius1014 requested changes
除了 comment 的没有什么问题。

2020-06-23 10:57 UTC, carassius1014 commented on my-base/src/My/Data/List.hs
> +-- "one\ntwo\n"
像 `lines` 和 `unlines` 这一对函数可以写性质测试。
``` 
prop>  (unlines . lines) str == str
```

2020-06-23 10:57 UTC, carassius1014 commented on my-base/src/My/Data/Tuple.hs
> +  (_,f) <*> (a,b) = (a, (f b))
想想为什么要限定 `Monoid a`。

2020-06-23 15:25 UTC, zhouyu843 commented on my-base/src/My/Data/Tuple.hs
> +  (_,f) <*> (a,b) = (a, (f b))
这个不符合结合律，交换律，修改了。

2020-06-23 15:35 UTC, zhouyu843 commented on my-base/src/My/Data/List.hs
> +-- "one\ntwo\n"
试了，不行。用本身的库也不行。
```haskell
*Main Prelude Data.List> lines "a"
["a"]
*Main Prelude Data.List> unlines ["a"]
"a\n"
```

2020-06-24 05:59 UTC, carassius1014 requested changes
除了这点应该没问题了......

2020-06-24 05:59 UTC, carassius1014 commented on my-base/src/My/Control/Applicative.hs
> +(<*) = const
一开始没发现。
按照这个写法的话由于 Haskell 是非严格评价所以 `a <* b` 里的 `b` 永远不会被计算。
虽然结果不需要 `b` 的值，但是 `f b` 里 `f` 的“副作用” 还是要保留的。

2020-06-24 06:00 UTC, carassius1014 commented on my-base/src/My/Control/Applicative.hs
> +(<*) = const
然后 '(*>)' 也是一样。

2020-06-24 10:44 UTC, zhouyu843 commented on my-base/src/My/Control/Applicative.hs
> +(<*) = const
修改了。
`(*>)`是 `flip (<*)`，所以不用改吧。

2020-06-24 11:02 UTC, carassius1014 commented on my-base/src/My/Control/Applicative.hs
> +(<*) = const
对

2020-06-24 11:05 UTC, carassius1014 approved these changes
Okey-dokey!

2020-06-24 11:07 UTC, merged